### ISSUE TITLE
No pairing 47PFK6549/12 (2014 Model)

### ISSUE THREAD

**Issue by wlauvenberg** [lucasvdh/codes.lucasvdh.philips-jointspace#15]
Model: 47PFK6549/12 (releasedate: 15 april 2014)
Software: QN141E_012.003.086.128 (latest)

**JointSpace API URLs**
http://192.168.1.18:1925/1/system
```
{
	"menulanguage": "Dutch",
	"name": "PHILIPS TV WK",
	"country": "Netherlands",
	"serialnumber_encrypted": "K2kseVsmQFgkd15gKkJ+auKHdtlei10XlUrmzvvKqgw=",
	"softwareversion_encrypted": "K2kseVsmQFgkd15gKkJ+aqCKXTYmH6lVxBPjS/ok9gL84V+2r6G1rP9iSaFqnwp8",
	"model_encrypted": "K2kseVsmQFgkd15gKkJ+aqKtb/+Cehh1vCMJCN1c8Rs=",
	"deviceid_encrypted": "K2kseVsmQFgkd15gKkJ+ajChDrDH1UwWpzLiZ/M1V4Q=",
	"nettvversion": "4.4.1",
	"epgsource": "broadcast"
}
```
http://192.168.1.18:1925/[2-6]/system
```
Forbidden
```

**Testscript**
```
c:\GitHub\codes.lucasvdh.philips-jointspace>node tests/pairing.js
? What's your TV's IP? 192.168.1.18
? What's your API version? (1 to 6) 1
? What port number should be used? Either 1925 or 1926 1925
Updating _client config
Sending system info call
[
  'GET [http://192.168.1.18:1925/1/system]',
  'with:',
  {},
  'requested securely?',
  false
]
[
  'GET [http://192.168.1.18:1925/1/system]',
  'with:',
  {},
  'requested securely?',
  false
]
[ 'user regular _client' ]
[ 'user regular _client' ]
```

[log.txt](https://github.com/lucasvdh/codes.lucasvdh.philips-jointspace/files/4035373/log.txt)

**Comment by lucasvdh** [comment]
@wlauvenberg is this the entire response that you get from http://192.168.1.18:1925/1/system ?
```json
{
	"menulanguage": "Dutch",
	"name": "PHILIPS TV WK",
	"country": "Netherlands",
	"serialnumber_encrypted": "K2kseVsmQFgkd15gKkJ+auKHdtlei10XlUrmzvvKqgw=",
	"softwareversion_encrypted": "K2kseVsmQFgkd15gKkJ+aqCKXTYmH6lVxBPjS/ok9gL84V+2r6G1rP9iSaFqnwp8",
	"model_encrypted": "K2kseVsmQFgkd15gKkJ+aqKtb/+Cehh1vCMJCN1c8Rs=",
	"deviceid_encrypted": "K2kseVsmQFgkd15gKkJ+ajChDrDH1UwWpzLiZ/M1V4Q=",
	"nettvversion": "4.4.1",
	"epgsource": "broadcast"
}
```

**Comment by wlauvenberg** [comment]
Yes, this is the only response.

`{ 	"menulanguage": "Dutch", 	"name": "PHILIPS TV WK", 	"country": "Netherlands", 	"serialnumber_encrypted": "K2kseVsmQFgkd15gKkJ+auKHdtlei10XlUrmzvvKqgw=", 	"softwareversion_encrypted": "K2kseVsmQFgkd15gKkJ+aqCKXTYmH6lVxBPjS/ok9gL84V+2r6G1rP9iSaFqnwp8", 	"model_encrypted": "K2kseVsmQFgkd15gKkJ+aqKtb/+Cehh1vCMJCN1c8Rs=", 	"deviceid_encrypted": "K2kseVsmQFgkd15gKkJ+ajChDrDH1UwWpzLiZ/M1V4Q=", 	"nettvversion": "4.4.1", 	"epgsource": "broadcast" }`

**Comment by lucasvdh** [comment]
Should be resolved in latest version.
