### ISSUE TITLE
phillips 47PFK7509/12

### ISSUE THREAD

**Issue by wesllleyyy** [lucasvdh/codes.lucasvdh.philips-jointspace#16]
I can't pair My tv. 
I have an phillips 47PFK7509/12
![Screenshot_20200409-162319](https://user-images.githubusercontent.com/61884590/78906566-ce5f2a80-7a7f-11ea-991a-b5e62ff30d21.jpg)
![Screenshot_20200409-162225](https://user-images.githubusercontent.com/61884590/78906582-d323de80-7a7f-11ea-9ebe-968c6b2c28f9.jpg)

Can you please help me?

**Comment by lucasvdh** [comment]
@wesllleyyy what response do you get if you navigate to this url at home?

http://192.168.178.184:1925/1/system and alternatively [**https**://192.168.178.184:1925/1/system](http://192.168.178.184:1925/1/system)

**Comment by wesllleyyy** [comment]
Hey lucas.

Ik krijg onderstaande meldingen terug

http://192.168.178.184:1925/1/system (bij alle andere versie nummers krijg ik forbidden terug)

{
        "menulanguage": "Dutch",
        "name": "PHILIPS TV",
        "country": "Netherlands",
        "serialnumber_encrypted": "K2kseVsmQFgkd15gKkJ+ahwhKmqRY2LdN9uonBKJI0s=",
        "softwareversion_encrypted": "K2kseVsmQFgkd15gKkJ+aqCKXTYmH6lVxBPjS/ok9gL84V+2r6G1rP9iSaFqnwp8",
        "model_encrypted": "K2kseVsmQFgkd15gKkJ+auqPu+SyWLZwbjqXIFMnsH8=",
        "deviceid_encrypted": "K2kseVsmQFgkd15gKkJ+apbmaRpLybGDybtHoKAvwso=",
        "nettvversion": "4.4.1",
        "epgsource": "broadcast"
}

https://192.168.178.184:1925/1/system<http://192.168.178.184:1925/1/system>

Deze site is niet bereikbaar
Bedankt alvast voor het nakijken!

Groetjes
________________________________
Van: Lucas van der Have <notifications@github.com>
Verzonden: donderdag 11 juni 2020 11:06
Aan: lucasvdh/codes.lucasvdh.philips-jointspace <codes.lucasvdh.philips-jointspace@noreply.github.com>
CC: wesllleyyy <weslleyy@live.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [lucasvdh/codes.lucasvdh.philips-jointspace] phillips 47PFK7509/12 (#16)


@wesllleyyy<https://github.com/wesllleyyy> what response do you get if you navigate to this url at home?

http://192.168.178.184:1925/1/system and alternatively https://192.168.178.184:1925/1/system<http://192.168.178.184:1925/1/system>
