### ISSUE TITLE
Volume control not working

### ISSUE THREAD

**Issue by ultimate-tester** [lucasvdh/codes.lucasvdh.philips-jointspace#19]
I have successfully paired my Philips 65OLED803, it has API version 6.
Almost everything is working (I didn't test literally every button) except for the volume control.
Both the slider, and the single buttons (Vol Up, Vol Down, Vol Mute) are not working at all.
They are also not giving any error message, but just nothing happens on the screen.

**Comment by PiTRiS87** [comment]
Created a pull request for this. If you want, just downlaod my branch and install it manually in your homey :)

**Comment by lucasvdh** [comment]
A fix for this issue is available in version `v0.3.8` and is awaiting approval. It is already available on [the test version of the app.](https://homey.app/a/codes.lucasvdh.philips-jointspace/test/)

https://github.com/lucasvdh/codes.lucasvdh.philips-jointspace/pull/23#issuecomment-812865583
