### ISSUE TITLE
On/Off Detection not working

### ISSUE THREAD

**Issue by ultimate-tester** [lucasvdh/codes.lucasvdh.philips-jointspace#20]
The on/off detection is not working. If I turn on the TV using the original remote, the Homey app still shows it's turned off.
Is there a way to synchronize the status? The reason I need this, is because I have Homey Flows connected to TV turn on/off and now it's not triggering except for when I turn on/off the TV with Homey specifically.

**Comment by lucasvdh** [comment]
A fix for this issue has been released in version `v0.3.7`.

https://github.com/lucasvdh/codes.lucasvdh.philips-jointspace/pull/21#issuecomment-810638260
