### ISSUE TITLE
Pairing does not work on 55PUS7101

### ISSUE THREAD

**Issue by renehagen** [lucasvdh/codes.lucasvdh.philips-jointspace#8]
Hello Lucas,

I installed the latest version from github. When pairing the pin shows up at the TV but if I try to sent the pin nothing happens. The view where I entered the PIN stays unchanged and I can keep clicking 'gegevens versturen' but nothing happens.

How can I get the logging to show up?

**Comment by lucasvdh** [comment]
Hi @renehagen there are two ways to debug this but they both require some technical knowledge.

### Option 1 - test script
_This requires that you have nodejs installed, see [https://nodejs.org/en/](https://nodejs.org/en/)_

Run the pairing test script in this repository ([/tests/pairing.js](https://github.com/lucasvdh/codes.lucasvdh.philips-jointspace/blob/beta)) on your pc or laptop with `nodejs`.

**Steps**
Clone or download the repository.
```
git clone git@github.com:lucasvdh/codes.lucasvdh.philips-jointspace.git
```
Navigate to the project folder in a terminal:
```
cd codes.lucasvdh.philips-jointspace
```
Run the test script with `nodejs`:
```
node tests/pairing.js
```
Then follow the steps of the pairing test script and post the `log.txt` file, which should be in the directory from where you ran the script, in this issue on github.

### Option 2 - run on your Homey
_This requires that you have [athom-cli](https://apps.developer.athom.com/tutorial-Getting%20Started.html) installed, see [https://apps.developer.athom.com/tutorial-Getting%20Started.html](https://apps.developer.athom.com/tutorial-Getting%20Started.html)_

You can install and run this app manually from your pc or laptop and see what happens/fails during the pairing process.

You can do this by clone or download the repository:
```
git clone git@github.com:lucasvdh/codes.lucasvdh.philips-jointspace.git
```
Then navigate to the project folder in a terminal:
```
cd codes.lucasvdh.philips-jointspace
```
And the install and run the app so you can see the logs:
```
athom app run
```
This takes a while. After the app app is installed you're be able to start the pairing process by adding your device in the Homey app. If anything fails it will be displayed in the terminal on your pc or laptop. Copy and paste the complete log from the beginnen of the pairing process here.

**Comment by lucasvdh** [comment]
I forgot to mention that you need to run `npm install` from inside the project's directory before you can run the command `node tests/pairing.js`.

**Comment by renehagen** [comment]
Thanks I will try this later this week and let you know the outcome.

Met vriendelijke groet,
René Hagen
Tel. 06-24551336
